# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 08:24
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tickets.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='カテゴリー名')),
                ('extra_fee_rate', models.FloatField(default=0, help_text='カテゴリーごとに持つ追加の販売手数料。0から1の小数で設定します。', verbose_name='カテゴリーごとの追加手数料')),
                ('display_priority', models.IntegerField(help_text='数字が大きいカテゴリーほど一覧表示で上位に表示されます。', verbose_name='表示優先度')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'ordering': ('-display_priority', 'name'),
                'verbose_name_plural': 'カテゴリー',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='チケット名')),
                ('start_date', models.DateField(verbose_name='開催日')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100), tickets.validators.StepValueValidator(100)], verbose_name='金額(円)')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='販売枚数(枚)')),
                ('status', models.PositiveIntegerField(choices=[(0, '出品中'), (1, '出品停止'), (2, '完売')], default=0, verbose_name='販売ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.Category', verbose_name='カテゴリー')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'チケット',
                'verbose_name_plural': 'チケット',
                'db_table': 'ticket',
            },
        ),
    ]
